package drools.issues;
import drools.issues.model.vehicles.*;

dialect "mvel"

rule "Gasoline vehicles with more than 95 kW use high-octane fuel"
    when
        $v:drools.issues.model.vehicles.GasolineVehicle(motor.kw > 95, score<=0, motor.highOctane == false)
    then
        System.out.println("Gasoline vehicle with more than 95 kW: " + $v+", score="+$v.score);
        $v.engine.highOctane = true;
        update($v);
end



rule "High octane engine vehicles have additional score"
    when
        $v:drools.issues.model.vehicles.GasolineVehicle(motor.highOctane == true, score<=0)
    then
        System.out.println("High octane engine vehicle: " + $v);
        $v.score = $v.score + 1;
        update($v);
end

rule "High-octane fuel engines newer serial numbers have slightly higher score"
    when
        $v:drools.issues.model.vehicles.GasolineVehicle(motor.highOctane == true, score<=1, $v.motor.serialNumber > 50000)
    then
        System.out.println("High octane engine vehicle with newer serial number: " + $v);
        $v.score = $v.score + 1;
        update($v);
end

rule "Max torque of engine cannot be higher than frame torque"
    when
        $v:drools.issues.model.vehicles.GasolineVehicle(motor.maxTorque > frameMaxTorque)
    then
        insert(new VehicleError($v, "Engine torque higher than frame torque"));
end